// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type CreateLabelInput struct {
	Name string `json:"name"`
}

type CreateProjectInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description"`
	Color       *string `json:"color"`
}

type CreateTaskInput struct {
	ProjectID    string        `json:"projectId"`
	ParentTaskID *string       `json:"parentTaskId"`
	Title        string        `json:"title"`
	Description  *string       `json:"description"`
	Status       *TaskStatus   `json:"status"`
	Priority     *TaskPriority `json:"priority"`
	StartAt      *time.Time    `json:"startAt"`
	DueAt        *time.Time    `json:"dueAt"`
	LabelIds     []string      `json:"labelIds"`
}

type DeletePayload struct {
	ID        string    `json:"id"`
	DeletedAt time.Time `json:"deletedAt"`
}

type Label struct {
	ID        string    `json:"id"`
	UserID    string    `json:"userId"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type LabelConnection struct {
	Edges    []*LabelEdge `json:"edges"`
	PageInfo *PageInfo    `json:"pageInfo"`
}

type LabelEdge struct {
	Cursor string `json:"cursor"`
	Node   *Label `json:"node"`
}

type PageInfo struct {
	EndCursor   *string `json:"endCursor"`
	HasNextPage bool    `json:"hasNextPage"`
}

type Project struct {
	ID          string    `json:"id"`
	UserID      string    `json:"userId"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	Color       *string   `json:"color"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type ProjectConnection struct {
	Edges    []*ProjectEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type ProjectEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Project `json:"node"`
}

type Task struct {
	ID           string       `json:"id"`
	UserID       string       `json:"userId"`
	ProjectID    string       `json:"projectId"`
	ParentTaskID *string      `json:"parentTaskId"`
	Title        string       `json:"title"`
	Description  *string      `json:"description"`
	Status       TaskStatus   `json:"status"`
	Priority     TaskPriority `json:"priority"`
	StartAt      *time.Time   `json:"startAt"`
	DueAt        *time.Time   `json:"dueAt"`
	CompletedAt  *time.Time   `json:"completedAt"`
	CreatedAt    time.Time    `json:"createdAt"`
	UpdatedAt    time.Time    `json:"updatedAt"`
	Labels       []*Label     `json:"labels"`
	Subtasks     []*Task      `json:"subtasks"`
}

type TaskConnection struct {
	Edges    []*TaskEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type TaskEdge struct {
	Cursor string `json:"cursor"`
	Node   *Task  `json:"node"`
}

type UpdateLabelInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UpdateProjectInput struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description"`
	Color       *string `json:"color"`
}

type UpdateTaskInput struct {
	ID          string        `json:"id"`
	Title       *string       `json:"title"`
	Description *string       `json:"description"`
	Status      *TaskStatus   `json:"status"`
	Priority    *TaskPriority `json:"priority"`
	StartAt     *time.Time    `json:"startAt"`
	DueAt       *time.Time    `json:"dueAt"`
	LabelIds    []string      `json:"labelIds"`
}

type UpsertMeInput struct {
	Name      string  `json:"name"`
	Email     string  `json:"email"`
	Timezone  string  `json:"timezone"`
	AvatarURL *string `json:"avatarUrl"`
}

type User struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Timezone  string    `json:"timezone"`
	AvatarURL *string   `json:"avatarUrl"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type TaskPriority string

const (
	TaskPriorityP1 TaskPriority = "P1"
	TaskPriorityP2 TaskPriority = "P2"
	TaskPriorityP3 TaskPriority = "P3"
	TaskPriorityP4 TaskPriority = "P4"
	TaskPriorityP5 TaskPriority = "P5"
)

var AllTaskPriority = []TaskPriority{
	TaskPriorityP1,
	TaskPriorityP2,
	TaskPriorityP3,
	TaskPriorityP4,
	TaskPriorityP5,
}

func (e TaskPriority) IsValid() bool {
	switch e {
	case TaskPriorityP1, TaskPriorityP2, TaskPriorityP3, TaskPriorityP4, TaskPriorityP5:
		return true
	}
	return false
}

func (e TaskPriority) String() string {
	return string(e)
}

func (e *TaskPriority) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskPriority(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskPriority", str)
	}
	return nil
}

func (e TaskPriority) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type TaskStatus string

const (
	TaskStatusTodo       TaskStatus = "TODO"
	TaskStatusInProgress TaskStatus = "IN_PROGRESS"
	TaskStatusBlocked    TaskStatus = "BLOCKED"
	TaskStatusDone       TaskStatus = "DONE"
)

var AllTaskStatus = []TaskStatus{
	TaskStatusTodo,
	TaskStatusInProgress,
	TaskStatusBlocked,
	TaskStatusDone,
}

func (e TaskStatus) IsValid() bool {
	switch e {
	case TaskStatusTodo, TaskStatusInProgress, TaskStatusBlocked, TaskStatusDone:
		return true
	}
	return false
}

func (e TaskStatus) String() string {
	return string(e)
}

func (e *TaskStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskStatus", str)
	}
	return nil
}

func (e TaskStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
