// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteTaskLabelsByLabelID(ctx context.Context, labelID pgtype.UUID) (int64, error)
	DeleteTaskLabelsForTask(ctx context.Context, taskID pgtype.UUID) error
	GetLabelByID(ctx context.Context, arg GetLabelByIDParams) (Label, error)
	GetLabelsByIDs(ctx context.Context, arg GetLabelsByIDsParams) ([]Label, error)
	GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error)
	GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	InsertTaskLabel(ctx context.Context, arg InsertTaskLabelParams) error
	ListLabels(ctx context.Context, arg ListLabelsParams) ([]Label, error)
	ListLabelsByTaskID(ctx context.Context, arg ListLabelsByTaskIDParams) ([]Label, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	ListRootTasks(ctx context.Context, arg ListRootTasksParams) ([]Task, error)
	ListSubtasks(ctx context.Context, arg ListSubtasksParams) ([]Task, error)
	ListSubtasksByParentID(ctx context.Context, arg ListSubtasksByParentIDParams) ([]Task, error)
	SoftDeleteDirectSubtasks(ctx context.Context, arg SoftDeleteDirectSubtasksParams) (int64, error)
	SoftDeleteLabel(ctx context.Context, arg SoftDeleteLabelParams) (SoftDeleteLabelRow, error)
	SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (SoftDeleteProjectRow, error)
	SoftDeleteTask(ctx context.Context, arg SoftDeleteTaskParams) (SoftDeleteTaskRow, error)
	SoftDeleteTasksByProject(ctx context.Context, arg SoftDeleteTasksByProjectParams) (int64, error)
	UpdateLabel(ctx context.Context, arg UpdateLabelParams) (Label, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpsertUserByEmail(ctx context.Context, arg UpsertUserByEmailParams) (User, error)
}

var _ Querier = (*Queries)(nil)
