// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: task_labels.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTaskLabelsForTask = `-- name: DeleteTaskLabelsForTask :exec
DELETE FROM task_labels
WHERE task_id = $1
`

func (q *Queries) DeleteTaskLabelsForTask(ctx context.Context, taskID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskLabelsForTask, taskID)
	return err
}

const insertTaskLabel = `-- name: InsertTaskLabel :exec
INSERT INTO task_labels (task_id, label_id)
VALUES ($1, $2)
ON CONFLICT (task_id, label_id) DO NOTHING
`

type InsertTaskLabelParams struct {
	TaskID  pgtype.UUID `json:"task_id"`
	LabelID pgtype.UUID `json:"label_id"`
}

func (q *Queries) InsertTaskLabel(ctx context.Context, arg InsertTaskLabelParams) error {
	_, err := q.db.Exec(ctx, insertTaskLabel, arg.TaskID, arg.LabelID)
	return err
}
