// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, timezone, avatar_url, created_at, updated_at, deleted_at
FROM users
WHERE email = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Timezone,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, timezone, avatar_url, created_at, updated_at, deleted_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Timezone,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertUserByEmail = `-- name: UpsertUserByEmail :one
INSERT INTO users (name, email, timezone, avatar_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (email) DO UPDATE
SET
  name = EXCLUDED.name,
  timezone = EXCLUDED.timezone,
  avatar_url = EXCLUDED.avatar_url,
  deleted_at = NULL,
  updated_at = NOW()
RETURNING id, name, email, timezone, avatar_url, created_at, updated_at, deleted_at
`

type UpsertUserByEmailParams struct {
	Name      string  `json:"name"`
	Email     string  `json:"email"`
	Timezone  string  `json:"timezone"`
	AvatarUrl *string `json:"avatar_url"`
}

func (q *Queries) UpsertUserByEmail(ctx context.Context, arg UpsertUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByEmail,
		arg.Name,
		arg.Email,
		arg.Timezone,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Timezone,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
